### ISSUE TITLE
Commands aren't processed from the default configuration

### ISSUE THREAD

**Issue by schmidtw** [schmidtw/goschtalt#3]
The secrets and other commands aren't being processed when they appear in the default configuration.

Example:
```yaml
---
# This is an example of documentation and default configuration.
# this defenition can live somewhere else, outside of this file
# or could be generated from a different file.  The choice is
# yours.

Example:
  # color can be one of [ red, green, blue ]
  color: blue # default to a popular color
  crayons ((secret)): box of 24
```

File 11.yml has a secret & it is redacted correctly.

Results in this:
`-----BEGIN REDACTED UNIFIED CONFIGURATION-----`
```yaml
car: # 11.yml:1[1]
    barn: REDACTED
example: # 000.yml:7[1]
    color: blue # 000.yml:9[10]
    crayons ((secret)): box of 24 # 000.yml:10[23]
```
`-----END REDACTED UNIFIED CONFIGURATION-----`
